#!/bin/zsh
############################################################### Z-shell exports

### Term
# if infocmp alacritty-direct >/dev/null 2>&1; then
#     export TERM='alacritty-direct';
if infocmp xterm-256color >/dev/null 2>&1; then
    export TERM='xterm-256color';
elif [[ $COLORTERM = gnome-* && $TERM = xterm* ]] && infocmp gnome-256color >/dev/null 2>&1; then
	  export TERM='gnome-256color';
fi;

### History
# Increase zsh history size to 16^4 entries
export HISTFILE="${XDG_CONFIG_HOME}/zshrc/histfile"
export HISTTIMEFORMAT="%Y/%m/%d %H:%M:%S:   "
export HISTSIZE=65536
export SAVEHIST=$HISTSIZE

# Cache
# zstyle ':completion:*' cache-path ${XDG_CACHE_HOME}/zsh/zcompcache

# Initialize zoxide
command -v zoxide &> /dev/null && eval "$(zoxide init zsh)"
