#!/bin/zsh
####################################################### zshrc

####################################################### Source the dotfiles
# Note: use shell/xauto to automatically start xorg-server when logging in
for file in ${XDG_CONFIG_HOME:=$HOME/.config}/{shell/path,shell/colors,shell/exports,zshrc/exports,zshrc/prompt,shell/functions,shell/aliases}; do
    [ -r "$file" ] && [ -f "$file" ] && . "$file"
done;
unset file;

for file in ${HOME}/local/bin/resolution_tty; do
    [ -r "$file" ] && [ -f "$file" ] && . "$file"
done;
unset file;


####################################################### General settings
# Lines configured by zsh-newuser-install
setopt autocd extendedglob notify
unsetopt beep nomatch
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
# zstyle :compinstall filename '/home/phdenzel/.zshrc'
zstyle :compinstall filename '${HOME}/.config/zshrc/zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# History
# - ignore duplicates
# - ignore commands starting with spaces
# - remove blank lines
# - append to history immediately
# - share history with other sessions
setopt hist_ignore_all_dups hist_ignore_space hist_reduce_blanks
setopt inc_append_history share_history
