[colors.normal]
red = "#FF6D6B"
green = "#44BC84"
yellow = "#FFD787"
blue = "#5F8AF7"
magenta = "#E83A82"
cyan = "#4DB5BD"
white = "#EDF3FE"
black = "#1D1D1F"

[colors.bright]
red = "#D7005F"
green = "#00AF87"
yellow = "#FDB760"
blue = "#5F5FFF"
magenta = "#FF0087"
cyan = "#46D9FF"
white = "#F6F9FE"
black = "#2E353A"

[colors.dim]
red = "#D70000"
green = "#3DAA77"
yellow = "#F69927"
blue = "#3723B7"
magenta = "#D7005F"
cyan = "#1F5582"
white = "#DDE3EE"
black = "#090B0E"

[colors.primary]
background = "#1D1D1F"
bright_foreground = "#F6F9FE"
dim_foreground = "#6D6D6D"
foreground = "#BDC3CE"

[colors.cursor]
cursor = "#5F8AF7"
text = "CellBackground"

[colors.line_indicator]
background = "None"
foreground = "None"

# [colors.search."colors.footer_bar"]
# background = "#353642"
# foreground = "#4DB5BD"

[colors.search.focused_match]
background = "#FDB760"
foreground = "#353642"

[colors.search.matches]
background = "#353642"
foreground = "#FDB760"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "#E83A82"
text = "CellBackground"
