[font]
size = 11

[font.bold]
family = "Fira Mono"
style = "Bold"

[font.bold_italic]
family = "Fira Mono"
style = "Bold Italic"

[font.italic]
family = "Firal Mono"
style = "Italic"

[font.normal]
family = "Fira Mono"
style = "Regular"

[font.offset]
x = 0
y = 0
